### ISSUE TITLE
Why comment out the include-guard?

### ISSUE THREAD

**Issue by gfixler** [sjl/tslime2.vim#2]
You have this line in autoload/tslime/core.tim:

```
; (ph/include-guard g:loaded-tslime)
```

I'm just wondering if there's a reason you have it commented out, as I'm playing with writing a .tim plugin right now. Any issues with it?

**Comment by sjl** [comment]
It's so I can develop the plugin and just source the file to reload it.  Usually I try to remember to uncomment it before I commit but sometimes I forget.
